/**
 * Created by roije on 08/10/2016.
 */
/**
 * Created by roije on 06/10/2016.
 */
export const internships: any[] = [

  {_id: 11,
    initials: 'chrk',
    email: 'chrk@kea.dk',
    visitDate: '11/12/16',
    nameOfStudent: 'Bob',
    companyName: 'TechSec',
    namesOfPersons: 'John Johnsen, Lars Poulsen',
    companyVision: '',
    companyCompetenceNeed: 'They need programmers who know how to use the ASP .NET MVC5 Framework',
    studentComptence: 'Scrum, ASP .NET MVC5, Java, Javascript',
    collabOpportunities: '',
    otherComments: ''},

  {_id: 12,
    initials: 'abcd',
    email: 'chrk@kea.dk',
    visitDate: '11/12/16',
    nameOfStudent: 'Bob',
    companyName: 'TechSec',
    namesOfPersons: 'John Johnsen, Lars Poulsen',
    companyVision: '',
    companyCompetenceNeed: 'They need programmers who know how to use the ASP .NET MVC5 Framework',
    studentComptence: 'Scrum, ASP .NET MVC5, Java, Javascript',
    collabOpportunities: '',
    otherComments: ''},

  {_id: 13,
    initials: 'efgh',
    email: 'chrk@kea.dk',
    visitDate: '11/12/16',
    nameOfStudent: 'Bob',
    companyName: 'TechSec',
    namesOfPersons: 'John Johnsen, Lars Poulsen',
    companyVision: '',
    companyCompetenceNeed: 'They need programmers who know how to use the ASP .NET MVC5 Framework',
    studentComptence: 'Scrum, ASP .NET MVC5, Java, Javascript',
    collabOpportunities: '',
    otherComments: ''},

  {_id: 14,
    initials: 'isjk',
    email: 'chrk@kea.dk',
    visitDate: '11/12/16',
    nameOfStudent: 'Bob',
    companyName: 'TechSec',
    namesOfPersons: 'John Johnsen, Lars Poulsen',
    companyVision: '',
    companyCompetenceNeed: 'They need programmers who know how to use the ASP .NET MVC5 Framework',
    studentComptence: 'Scrum, ASP .NET MVC5, Java, Javascript',
    collabOpportunities: '',
    otherComments: ''},

  {_id: 15,
    initials: 'qwer',
    email: 'chrk@kea.dk',
    visitDate: '11/12/16',
    nameOfStudent: 'Bob',
    companyName: 'TechSec',
    namesOfPersons: 'John Johnsen, Lars Poulsen',
    companyVision: '',
    companyCompetenceNeed: 'They need programmers who know how to use the ASP .NET MVC5 Framework',
    studentComptence: 'Scrum, ASP .NET MVC5, Java, Javascript',
    collabOpportunities: '',
    otherComments: ''},

  {_id: 16,
    initials: 'ghjl',
    email: 'chrk@kea.dk',
    visitDate: '11/12/16',
    nameOfStudent: 'Bob',
    companyName: 'TechSec',
    namesOfPersons: 'John Johnsen, Lars Poulsen',
    companyVision: '',
    companyCompetenceNeed: 'They need programmers who know how to use the ASP .NET MVC5 Framework',
    studentComptence: 'Scrum, ASP .NET MVC5, Java, Javascript',
    collabOpportunities: '',
    otherComments: ''},

  {_id: 17,
    initials: 'bvbv',
    email: 'chrk@kea.dk',
    visitDate: '11/12/16',
    nameOfStudent: 'Bob',
    companyName: 'TechSec',
    namesOfPersons: 'John Johnsen, Lars Poulsen',
    companyVision: '',
    companyCompetenceNeed: 'They need programmers who know how to use the ASP .NET MVC5 Framework',
    studentComptence: 'Scrum, ASP .NET MVC5, Java, Javascript',
    collabOpportunities: '',
    otherComments: ''},

  {_id: 18,
    initials: 'mnmn', email: 'chrk@kea.dk',
    visitDate: '11/12/16',
    nameOfStudent: 'Bob',
    companyName: 'TechSec',
    namesOfPersons: 'John Johnsen, Lars Poulsen',
    companyVision: '',
    companyCompetenceNeed: 'They need programmers who know how to use the ASP .NET MVC5 Framework',
    studentComptence: 'Scrum, ASP .NET MVC5, Java, Javascript',
    collabOpportunities: '',
    otherComments: ''},

  {_id: 19,
    initials: 'aaaa',
    email: 'chrk@kea.dk',
    visitDate: '11/12/16',
    nameOfStudent: 'Bob',
    companyName: 'TechSec',
    namesOfPersons: 'John Johnsen, Lars Poulsen',
    companyVision: '',
    companyCompetenceNeed: 'They need programmers who know how to use the ASP .NET MVC5 Framework',
    studentComptence: 'Scrum, ASP .NET MVC5, Java, Javascript',
    collabOpportunities: '',
    otherComments: ''},

  {_id: 20,
    initials: 'wwww',
    email: 'chrk@kea.dk',
    visitDate: '11/12/16',
    nameOfStudent: 'Bob',
    companyName: 'TechSec',
    namesOfPersons: 'John Johnsen, Lars Poulsen',
    companyVision: '',
    companyCompetenceNeed: 'They need programmers who know how to use the ASP .NET MVC5 Framework',
    studentComptence: 'Scrum, ASP .NET MVC5, Java, Javascript',
    collabOpportunities: '',
    otherComments: ''},

  {_id: 21,
    initials: 'qqqq',
    email: 'chrk@kea.dk',
    visitDate: '11/12/16',
    nameOfStudent: 'Bob',
    companyName: 'TechSec',
    namesOfPersons: 'John Johnsen, Lars Poulsen',
    companyVision: '',
    companyCompetenceNeed: 'They need programmers who know how to use the ASP .NET MVC5 Framework',
    studentComptence: 'Scrum, ASP .NET MVC5, Java, Javascript',
    collabOpportunities: '',
    otherComments: ''
  },

  {_id: 22,
    initials: 'eeee',
    email: 'chrk@kea.dk',
    visitDate: '11/12/16',
    nameOfStudent: 'Bob',
    companyName: 'TechSec',
    namesOfPersons: 'John Johnsen, Lars Poulsen',
    companyVision: '',
    companyCompetenceNeed: 'They need programmers who know how to use the ASP .NET MVC5 Framework',
    studentComptence: 'Scrum, ASP .NET MVC5, Java, Javascript',
    collabOpportunities: '',
    otherComments: ''},

  {_id: 23,
    initials: 'rrrr',
    email: 'chrk@kea.dk',
    visitDate: '11/12/16',
    nameOfStudent: 'Bob',
    companyName: 'TechSec',
    namesOfPersons: 'John Johnsen, Lars Poulsen',
    companyVision: '',
    companyCompetenceNeed: 'They need programmers who know how to use the ASP .NET MVC5 Framework',
    studentComptence: 'Scrum, ASP .NET MVC5, Java, Javascript',
    collabOpportunities: '',
    otherComments: ''},

  {_id: 24,
    initials: 'tttt',
    email: 'chrk@kea.dk',
    visitDate: '11/12/16',
    nameOfStudent: 'Bob',
    companyName: 'TechSec',
    namesOfPersons: 'John Johnsen, Lars Poulsen',
    companyVision: '',
    companyCompetenceNeed: 'They need programmers who know how to use the ASP .NET MVC5 Framework',
    studentComptence: 'Scrum, ASP .NET MVC5, Java, Javascript',
    collabOpportunities: '',
    otherComments: ''},

  {_id: 25,
    initials: 'yyyy',
    email: 'chrk@kea.dk',
    visitDate: '11/12/16',
    nameOfStudent: 'Bob',
    companyName: 'TechSec',
    namesOfPersons: 'John Johnsen, Lars Poulsen',
    companyVision: '',
    companyCompetenceNeed: 'They need programmers who know how to use the ASP .NET MVC5 Framework',
    studentComptence: 'Scrum, ASP .NET MVC5, Java, Javascript',
    collabOpportunities: '',
    otherComments: ''},

];
